USE XWORKZ;
CREATE TABLE COLLEGE(ID INT,COLLEGE_ID VARCHAR(10),
COLLEGE_NAME VARCHAR(40),LOCATION VARCHAR(30),NO_OF_BRANCHES INT,NO_OF_STUDENTS INT);
DESC COLLEGE;
INSERT INTO COLLEGE VALUES(1,'4UB','UBDT COLLEGE OF ENGINNERING','DAVANAGERE',7,2000);
INSERT INTO COLLEGE VALUES(3,'4J','JAIN COLLEGE','DAVANAGERE',7,2000);
INSERT INTO COLLEGE VALUES(4,'4GM','GM IT','DAVANAGERE',6,2000);

INSERT INTO COLLEGE VALUES
(5,'4JN','JNN CE ','SHIVAMOGGA',8,1000);

INSERT INTO COLLEGE VALUES(6,'4UB','UBDT ','DAVANAGERE',7,4000);
INSERT INTO COLLEGE VALUES(7,'4MS','M SIT','BENGALURU',13,7000);
INSERT INTO COLLEGE VALUES(8,'4BMS','BMS COLLEGE ','BENAGLURU',12,2000);
INSERT INTO COLLEGE VALUES(9,'4DY','DAYANDA SAGAR','BENAGLURU',11,3000);
INSERT INTO COLLEGE VALUES(11,'4NM','NMIT ','KARKALA',10,3000);
INSERT INTO COLLEGE VALUES(12,'4BP','PES','MANDYA',7,1000);
INSERT INTO COLLEGE VALUES(13,'4J','JSS ACCDEMY''MYSORE',7,2000);
INSERT INTO COLLEGE VALUES(16,'4UB','ALVAS','MANGALURU',7,4000);
INSERT INTO COLLEGE VALUES(17,'4MS','NITTE MEENAKSHI','BENGALURU',13,7000);
INSERT INTO COLLEGE VALUES(20,'4AT','ATRIA  ','BENAGALURU',10,3000);
SELECT * FROM college;

CREATE TABLE STUDENT(ID INT,STUDENT_ID INT,STUDENT_NAME VARCHAR(30),COLLEGE VARCHAR(30),
BRANCH VARCHAR(15),GRADE VARCHAR(5));

INSERT INTO STUDENT VALUES(1,101,'VIKAS','UBDT','EEE','A');
INSERT INTO STUDENT VALUES
(1,101,'VIKAS','UBDT','EEE','A'),
(2,102,'ABI','SVIT','CSE','A'),
(3,103,'ASHOK','BMS','EC','B'),
(4,104,'BALAJI','RNS','MECH','A'),
(5,105,'ARUN','UBDT','CIVIL','B');
INSERT INTO STUDENT VALUES
(6,106,'VIKAS','UBDT','EEE','A'),
(7,107,'ABI','SVIT','CSE','A'),
(8,108,'ASHOK','BMS','EC','B'),
(9,109,'BALAJI','RNS','MECH','A'),
(10,110,'ARUN','UBDT','CIVIL','B');