USE ASSIGNMENTS;
CREATE TABLE ORDERR(ID INT,ORDER_NAME VARCHAR(30),COST BIGINT,ORDER_ID INT PRIMARY KEY,
CREATED_AT TIMESTAMP,
CREATED_BY VARCHAR(30),MODIFIED_AT TIMESTAMP,MODIFIED_BY TIMESTAMP);

CREATE TABLE PAYMENT(ID INT,PRICE BIGINT,PAYMENT_ID INT,PAYMENT_STATUS VARCHAR(30),
CREATED_AT TIMESTAMP,
CREATED_BY VARCHAR(30),MODIFIED_AT TIMESTAMP,MODIFIED_BY TIMESTAMP,ORDER_ID INT,foreign key(ORDER_ID)
 references ORDERR(ORDER_ID),PRIMARY KEY(PAYMENT_ID));
 
 DESC PAYMENT;
 DROP TABLE PAYMENT;
 
 CREATE TABLE RESTURENT(ID INT,RESTURENT_NAME VARCHAR(30),RESTURENT_ID INT,LOCATION VARCHAR(30),ORDER_ID
 INT,RATINGS VARCHAR(30),PAYMENT_ID INT,
 CREATED_AT TIMESTAMP,
CREATED_BY VARCHAR(30),MODIFIED_AT TIMESTAMP,MODIFIED_BY VARCHAR(30),
FOREIGN KEY(ORDER_ID) references ORDERR(ORDER_ID),
FOREIGN KEY(PAYMENT_ID) references PAYMENT(PAYMENT_ID),
PRIMARY KEY(RESTURENT_ID));

CREATE TABLE DELIVARY (
  ID INT,
  PERSON_NAME VARCHAR(30),
  MODE_OF_PAYMENT ENUM('CASH', 'ONLINE'),
  RESTURENT_ID INT,
  ORDER_ID INT,
  CREATED_AT TIMESTAMP,
  CREATED_BY VARCHAR(30),
  MODIFIED_AT TIMESTAMP,
  MODIFIED_BY VARCHAR(30),
  FOREIGN KEY (RESTURENT_ID) REFERENCES PAYMENT(PAYMENT_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERR(ORDER_ID)
);
DROP TABLE delivary;

SELECT * FROM ORDERR;
DESC ORDERR;
ALTER TABLE ORDERR MODIFY COLUMN MODIFIED_BY VARCHAR(30);
INSERT INTO ORDERR VALUES(1,'MOBILE ORDER',20000,101,now(),'NAYANA',NOW(),'NAYANA');
INSERT INTO ORDERR VALUES(2,'TEA SHIRT ORDER',200,102,now(),'NAYANA',NOW(),'NAYANA');
INSERT INTO ORDERR VALUES(3,'HAIROIL ORDER',250,103,now(),'NAYANA',NOW(),'NAYANA');
INSERT INTO ORDERR VALUES(4,'CLOTH ORDER',2000,104,now(),'NAYANA',NOW(),'NAYANA'),
(5,'GROCIRIES ORDER',4000,105,now(),'NAYANA',NOW(),'NAYANA'),
(6,'COSEMETICS ORDER',4500,106,now(),'NAYANA',NOW(),'NAYANA'),
(7,'SKINCARE ORDER',6000,107,now(),'NAYANA',NOW(),'NAYANA'),
(8,'TV ORDER',45000,108,now(),'NAYANA',NOW(),'NAYANA'),
(9,'ELECTRONIC GADGETS ORDER',40000,109,now(),'NAYANA',NOW(),'NAYANA'),
(10,'SHAMPOO ORDER',6000,110,now(),'NAYANA',NOW(),'NAYANA');

SELECT * FROM PAYMENT;
DESC PAYMENT;
ALTER TABLE PAYMENT MODIFY COLUMN MODIFIED_BY VARCHAR(30);
INSERT INTO PAYMENT VALUES(1,200,201,'SUCCES',NOW(),'SNEHA',NOW(),'SUSHMITA',110);
INSERT INTO PAYMENT VALUES
(2,3500,202,'SUCCES',NOW(),'SNEHA',NOW(),'SUSHMITA',108),
(3,350,203,'PENDING',NOW(),'SNEHA',NOW(),'SUSHMITA',105),
(4,1900,204,'FAILED',NOW(),'SNEHA',NOW(),'SUSHMITA',102),
(5,890,205,'SUCCES',NOW(),'SNEHA',NOW(),'SUSHMITA',107),
(6,450,206,'SUCCES',NOW(),'SNEHA',NOW(),'SUSHMITA',101),
(7,3500,207,'PENDING',NOW(),'SNEHA',NOW(),'SUSHMITA',102),
(8,987,208,'FAIL',NOW(),'SNEHA',NOW(),'SUSHMITA',108),
(9,3590,209,'SUCCES',NOW(),'SNEHA',NOW(),'SUSHMITA',108),
(10,799,210,'FAIL',NOW(),'SNEHA',NOW(),'SUSHMITA',109);

DESC RESTURENT;

INSERT INTO RESTURENT VALUES(1,'UDUPI RESTURENT',801,'UDUPI',101,'3 STAR'
,209,NOW(),'KIRAN',NOW(),'BAAJI');
INSERT INTO RESTURENT VALUES
(2,'UDUPI RESTURENT',802,'DANDELI',105,'3 STAR',201,NOW(),'KIRAN',NOW(),'BAAJI'),
(3,'UDUPI UPAHARA',803,'MANGALURU',106,'3 STAR',208,NOW(),'KIRAN',NOW(),'BAAJI'),
(4,'KARAVALI RESTURENT',804,'BENGALURY',108,'3 STAR',209,NOW(),'KIRAN',NOW(),'BAAJI'),
(5,'MALANAD RESTURENT',805,'THIRTHAHALLI',110,'3 STAR',210,NOW(),'KIRAN',NOW(),'BAAJI'),
(6,'UTTARAKANNA RESTURENT',806,'HOSANGARA',109,'3 STAR',203,NOW(),'KIRAN',NOW(),'BAAJI'),
(7,'SIRASI VEG RESTURENT',807,'HARIHAR',104,'3 STAR',205,NOW(),'KIRAN',NOW(),'BAAJI'),
(8,'KIRAN  RESTURENT',808,'DAVANAGERE',101,'3 STAR',206,NOW(),'KIRAN',NOW(),'BAAJI'),
(9,'GOLDEN VIEW RESTURENT',809,'HUBLI',104,'3 STAR',206,NOW(),'KIRAN',NOW(),'BAAJI'),
(10,'SAGARA DOSE HALL',810,'SAGARA',102,'3 STAR',205,NOW(),'KIRAN',NOW(),'BAAJI');
 SELECT * FROM RESTURENT;

DESC DELIVARY;
SELECT * FROM ORDERR;
 
 INSERT INTO DELIVARY VALUES (1, 'SUPREETH', 'CASH', 808, 102, NOW(), 'AROHI', NOW(), 'AMITH');
INSERT INTO DELIVARY VALUES (2, 'SUPREETH', 'CASH', 808, 102, NOW(), 'AROHI', NOW(), 'AMITH');
INSERT INTO DELIVARY VALUES (3, 'hani', 'CASH', 808, 102, NOW(), 'AROHI', NOW(), 'AMITH');
INSERT INTO DELIVARY VALUES (4, 'JAANU', 'ONLINE', 808, 102, NOW(), 'AROHI', NOW(), 'AMITH');
INSERT INTO DELIVARY VALUES (5, 'KUMAR', 'ONLINE', 808, 102, NOW(), 'AROHI', NOW(), 'AMITH');
INSERT INTO DELIVARY VALUES (6, 'ARN', 'ONLINE', 808, 102, NOW(), 'AROHI', NOW(), 'AMITH');
INSERT INTO DELIVARY VALUES (7, 'UDAY', 'CASH', 808, 102, NOW(), 'AROHI', NOW(), 'AMITH');
INSERT INTO DELIVARY VALUES (8, 'AKASK', 'ONLINE', 808, 102, NOW(), 'AROHI', NOW(), 'AMITH');
INSERT INTO DELIVARY VALUES (9, 'RAJ', 'CASH', 808, 102, NOW(), 'AROHI', NOW(), 'AMITH');
INSERT INTO DELIVARY VALUES (10, 'RAVI', 'CASH', 808, 102, NOW(), 'AROHI', NOW(), 'AMITH');
 








