use assignments;
CREATE TABLE SHOP(ID INT,SHOP_NAME VARCHAR(20),SHOP_ID INT PRIMARY KEY,SERVICE VARCHAR(20));
DROP TABLE SHOP;

CREATE TABLE CUSTUMER(ID INT,CUSTOMER_NAME VARCHAR(30),PURCHASED_ITEM VARCHAR(30),SHOP_ID INT ,
FOREIGN KEY(SHOP_ID) references SHOP(SHOP_ID));

DESC SHOP;
INSERT INTO SHOP VALUES(1,'SHREE SHOPS',101,'GROCIRIES');
INSERT INTO SHOP VALUES(2,'KIRAN SHOPS',102,'BOOKSS');
INSERT INTO SHOP VALUES(3,'ABI SHOPS',103,'FOOD');
INSERT INTO SHOP VALUES(4,'SIDDU SHOPS',104,'PIPES');
INSERT INTO SHOP VALUES(5,'AMAR SHOPS',105,'CLOTHES');
INSERT INTO SHOP VALUES(6,'SHREE SHOPS',106,'GROCIRIES');
INSERT INTO SHOP VALUES(7,'KIRAN SHOPS',107,'BOOKSS');
INSERT INTO SHOP VALUES(8,'ABI SHOPS',108,'FOOD');
INSERT INTO SHOP VALUES(9,'SIDDU SHOPS',109,'PIPES');
INSERT INTO SHOP VALUES(10,'AMAR SHOPS',110,'CLOTHES');
INSERT INTO SHOP VALUES(11,'SHREE SHOPS',111,'GROCIRIES');
INSERT INTO SHOP VALUES(12,'KIRAN SHOPS',112,'BOOKSS');
INSERT INTO SHOP VALUES(13,'ABI SHOPS',113,'FOOD');
INSERT INTO SHOP VALUES(14,'SIDDU SHOPS',114,'PIPES');
INSERT INTO SHOP VALUES(15,'AMAR SHOPS',115,'CLOTHES');

DESC CUSTUMER;
INSERT INTO CUSTUMER VALUES(1,'ARUN','GRROCIRIES',105);
INSERT INTO CUSTUMER VALUES(2,'DARSHAN','PIPES',104);
INSERT INTO CUSTUMER VALUES(3,'APPORVA','ELECTRONICS',103);
INSERT INTO CUSTUMER VALUES(4,'SHREEDHARA','GRROCIRIES',102);
INSERT INTO CUSTUMER VALUES(5,'SHASHI','PHARMA',101);
INSERT INTO CUSTUMER VALUES(6,'KIRAN','GRROCIRIES',105);
INSERT INTO CUSTUMER VALUES(7,'JEEVA','BOOKS',104);
INSERT INTO CUSTUMER VALUES(8,'GOVIND','PHARMA',103);
INSERT INTO CUSTUMER VALUES(9,'YUVI','BOOKS',109);
INSERT INTO CUSTUMER VALUES(10,'YUVI','BOOKS',112);
INSERT INTO CUSTUMER VALUES(11,'YUVI','BOOKS',113);
INSERT INTO CUSTUMER VALUES(12,'YUVI','BOOKS',112);
INSERT INTO CUSTUMER VALUES(13,'YUVI','BOOKS',113);
INSERT INTO CUSTUMER VALUES(14,'YUVI','BOOKS',114);
INSERT INTO CUSTUMER VALUES(15,'YUVI','BOOKS',115);
DELETE FROM CUSTUMER WHERE SHOP_ID=101;

CREATE TABLE HOTEL(ID INT,HOTEL_NAME VARCHAR(20),HOTEL_ID INT PRIMARY KEY);
DROP TABLE HOTEL;

SELECT * FROM SHOP as S INNER JOIN CUSTUMER AS C ON S.SHOP_ID=C.SHOP_ID;


SELECT * FROM SHOP as S INNER JOIN CUSTUMER AS C ON S.SERVICE=C.PURCHASED_ITEM;

SELECT * FROM SHOP as S LEFT JOIN CUSTUMER AS C ON S.SHOP_ID=C.SHOP_ID;


SELECT * FROM SHOP as S RIGHT JOIN CUSTUMER AS C ON S.SHOP_ID=C.SHOP_ID;


CREATE TABLE HOTEL(ID INT,HOTEL_NAME VARCHAR(20),HOTEL_ID INT PRIMARY KEY);

CREATE TABLE HOTEL_LOCATION(ID INT,LOCATION VARCHAR(30),HOTEL_ID INT,
FOREIGN KEY(HOTEL_ID) references HOTEL(HOTEL_ID));

INSERT INTO HOTEL VALUES(1,'UDUPI SAGARA',101);
INSERT INTO HOTEL VALUES(2,'HOTEL AYODHYA',102);
INSERT INTO HOTEL VALUES(3,'UDUPI ',103);
INSERT INTO HOTEL VALUES(4,'AMBUJA',104);
INSERT INTO HOTEL VALUES(5,'RAMESHWARAM CAFE',105);

INSERT INTO HOTEL VALUES(6,'MALENAADU',106);
INSERT INTO HOTEL VALUES(7,'SAGARA',107);
INSERT INTO HOTEL VALUES(8,'MTR ',108);
INSERT INTO HOTEL VALUES(9,'SHIV TOFFIN ',109);
INSERT INTO HOTEL VALUES(10,'GURU KOTRESWARA',110);

INSERT INTO HOTEL VALUES(11,'ARABBI',111);
INSERT INTO HOTEL VALUES(12,'KARAVALI',112);
INSERT INTO HOTEL VALUES(13,'SHIV SAGAR ',113);
INSERT INTO HOTEL VALUES(14,'HALLI BENNE DOSE ',114);
INSERT INTO HOTEL VALUES(15,'GURU RAMESHWERA',115);

INSERT INTO HOTEL_LOCATION VALUES(1,'RAJAJI NAGAR',101);
INSERT INTO HOTEL_LOCATION VALUES(2,'SAGARA',105);
INSERT INTO HOTEL_LOCATION VALUES(3,'SHIVAMOGGA',104);
INSERT INTO HOTEL_LOCATION VALUES(4,'KUNDAPURA',103);
INSERT INTO HOTEL_LOCATION VALUES(5,'BELTHGANDY',102);

INSERT INTO HOTEL_LOCATION VALUES(6,'RAJAJI NAGAR',106);
INSERT INTO HOTEL_LOCATION VALUES(7,'MALLESHWARAM',107);
INSERT INTO HOTEL_LOCATION VALUES(8,'BTM',108);
INSERT INTO HOTEL_LOCATION VALUES(9,'HOSANAGARA',109);
INSERT INTO HOTEL_LOCATION VALUES(10,'DAVANAGERE',110);

INSERT INTO HOTEL_LOCATION VALUES(11,'HUBLI',101);
INSERT INTO HOTEL_LOCATION VALUES(12,'HAVERI',111);
INSERT INTO HOTEL_LOCATION VALUES(13,'KARKALA',114);
INSERT INTO HOTEL_LOCATION VALUES(14,'MADEKRI',113);
INSERT INTO HOTEL_LOCATION VALUES(15,'ANANDAPURA',115);

SELECT * FROM HOTEL A INNER JOIN HOTEL_LOCATION B ON A.HOTEL_ID=B.HOTEL_ID;

SELECT * FROM HOTEL A LEFT JOIN HOTEL_LOCATION B ON A.HOTEL_ID=B.HOTEL_ID;

SELECT * FROM HOTEL A RIGHT JOIN HOTEL_LOCATION B ON A.HOTEL_ID=B.HOTEL_ID;


SELECT * FROM HOTEL A FULL OUTER JOIN HOTEL_LOCATION B ON A.HOTEL_ID=B.HOTEL_ID;