USE ASSIGNMENTS;
/*TABLE 1*/
/*USAGE OF CONSTRAINTS WHILE CREATING TABLE*/
CREATE TABLE CRICKET(ID INT UNIQUE,TEAM_NAME VARCHAR(20)NOT NULL,TEAM_ID INT PRIMARY KEY,
NO_OF_PLAYERS INT,CAPTIAN VARCHAR(30),
 CONSTRAINT CAP_CHECK CHECK (NO_OF_PLAYERS >=11));
 SELECT * FROM CRICKET;
 
 /*USGAE OF CONSTRAINTS AFTER CREATING TABLE */
 ALTER TABLE CRICKET ADD COLUMN COUNTRY VARCHAR(30) NOT NULL;
ALTER TABLE CRICKET ADD COLUMN COUNTRY_CODE VARCHAR(30) UNIQUE;

DESC CRICKET;
INSERT INTO CRICKET VALUES(1,'TEAM INDIA',101,15,'ROHITH SHARMA','INDIA','91');
  INSERT INTO CRICKET VALUES
  (2,'TEAM SOUTH AFRICA',102,11,'MAKRAM','SOUTH AFRICA','99'),
  (3,'RCB',103,16,'FAF DUPLESSIS','INDIA','33'),
  (4,'CSK',104,12,'RUTHURAJ','INDIA','89'),
  (5,'MI',105,17,'HARDIK','INDIA','98');
  
  /*ADDING CONSTRANTS AFTER INSERTING DATA TO THE TABLE */
  ALTER TABLE CRICKET ADD COLUMN COATCH_ID INT;
  ALTER TABLE CRICKET  ADD CONSTRAINT  COACH_ID_UNI UNIQUE(COATCH_ID);
  
ALTER TABLE CRICKET ADD COLUMN COATCH_NAME VARCHAR(30);
ALTER TABLE CRICKET  ADD CONSTRAINT  COACH_NAME_NULL UNIQUE(COATCH_NAME);

ALTER TABLE CRICKET  DROP CONSTRAINT COUNTRY_CODE ;
SELECT * FROM CRICKET;

/*TABLE 2*/

CREATE TABLE STUDENT(ID INT UNIQUE,STUDENT_ID INT PRIMARY KEY,STUDENT_NAME VARCHAR(30) NOT NULL,
SCHOOL VARCHAR(30),AGE INT,SCHOOL_ID INT, 
CHECK(AGE>=5 )); 

ALTER TABLE STUDENT ADD CONSTRAINT SCOOL_ID_UNI UNIQUE(SCHOOL_ID);
ALTER TABLE STUDENT DROP CONSTRAINT SCOOL_ID_UNI;

DESC STUDENT;
INSERT INTO STUDENT VALUES(1,101,'DEEPU','JRM PUBLIC SCHOOL',6,201);
INSERT INTO STUDENT VALUES(2,102,'RRR PUBLIC SCHOOL',7,202);
DELETE FROM STUDENT WHERE ID=2;

ALTER TABLE STUDENT MODIFY COLUMN STUDENT_NAME VARCHAR(30) NOT NULL;
INSERT INTO STUDENT VALUES(3,103,'POORNA','SRI PUBLIC SCHOOL',6,203);
INSERT INTO STUDENT VALUES(4,104,'PAVITHRA','SAI PUBLIC SCHOOL',6,204);
INSERT INTO STUDENT VALUES(5,105,'PRAVEENA','ALOK PUBLIC SCHOOL',8,205);
INSERT INTO STUDENT VALUES(6,106,'PRAVEENA','ALOK PUBLIC SCHOOL',8,206);

ALTER TABLE STUDENT  ADD CONSTRAINT  SCHOOL_ID_UNI UNIQUE(SCHOOL_ID );
ALTER TABLE STUDENT  DROP CONSTRAINT SCHOOL_ID_UNI;

/*TABLE 3*/
CREATE TABLE DOCTOR(ID INT UNIQUE,DOCTOR_ID INT PRIMARY KEY, DOCTOR_NAME VARCHAR(20) NOT NULL,
SPECILAZATION VARCHAR(30),EXPIRENCE INT,AGE INT,CHECK(AGE <=62));

ALTER TABLE DOCTOR ADD CONSTRAINT SPECI_NOT UNIQUE(SPECILAZATION) ;
ALTER TABLE DOCTOR DROP CONSTRAINT SPECI_NOT;
DESC DOCTOR;

INSERT INTO DOCTOR VALUES(1,101,'PUSHPA','NEUROSPECIALIST',10,50),
(2,102,'KARTHIK','CARDIOLOGIST',20,57),
(3,103,'PRANITHA','ONKOLOGIST',12,60),
(4,104,'SHRUTHI','DENTIST',8,45),
(5,105,'SHREEDHA','GYNOCHOLOGIST',24,33);
SELECT * FROM DOCTOR;
ALTER TABLE DOCTOR  ADD CONSTRAINT  SPECILAIZATION_DOCTO UNIQUE(SPECILAZATION);
ALTER TABLE DOCTOR DROP   CONSTRAINT  SPECILAIZATION_DOCTO;

/*TABLE 4*/

CREATE TABLE COLLEGE(ID INT UNIQUE,COLLEGE_CODE VARCHAR(20),COLLEGE_NAME VARCHAR(30),
NO_OF_DEPARTMENTS INT,NO_OF_STUDENTS INT,PRIMARY KEY(COLLEGE_CODE),CHECK(NO_OF_DEPARTMENTS>=1));

ALTER TABLE COLLEGE ADD CONSTRAINT NO_STU_CHK CHECK( NO_OF_STUDENTS>=100);
ALTER TABLE COLLEGE DROP CONSTRAINT NO_STU_CHK;

DESC COLLEGE;
INSERT INTO COLLEGE VALUES(1,'4UB','UBDT',7,1000);
INSERT INTO COLLEGE VALUES(2,'4NM','NMIT',9,2000);
INSERT INTO COLLEGE VALUES(3,'4AMC','AMC',6,1500);
INSERT INTO COLLEGE VALUES(4,'5BMC','BMC',20,10000);
INSERT INTO COLLEGE VALUES(5,'2MSIT','MSIT',18,5000);

ALTER TABLE COLLEGE  ADD CONSTRAINT  SPECILAIZATION_DOCTO UNIQUE(SPECILAZATION);
